name: Android APK Build

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Patch dependencies
        run: node ./ci/patch-deps

      - name: Build JS bundle
        run: npm run bundle-rnjs

      - name: Setup build variables
        id: vars
        run: |
          VERSION_NAME=$(echo "${GITHUB_REF_NAME}" | sed 's/^v//')
          echo "version_name=$VERSION_NAME" >> $GITHUB_OUTPUT

      - name: Build APKs
        run: |
          USE_SPLITBUILD=1 \
          CI_BUILD=1 \
          CI_VERSION_NAME="${{ steps.vars.outputs.version_name }}" \
          ./gradlew assembleRelease --no-daemon

      - name: Build AAB
        run: |
          ./gradlew bundleRelease --no-daemon

      - name: Upload APK Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: APK-Files
          path: |
            app/build/outputs/apk/release/*.apk

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AAB-File
          path: |
            app/build/outputs/bundle/release/*.aab

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            app/build/outputs/apk/release/*.apk
            app/build/outputs/bundle/release/*.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
